### ISSUE TITLE
Embrace ES Modules in the Backend

### ISSUE THREAD

**Issue by kutyel** [clevertech/boilerplate#15]
Hi!

I think it's a nice to have since thanks to [`esm`](https://www.npmjs.com/package/esm) we can now fully embrace ECMAScript imports/exports both in the frontend and in the backend. 😉 

I've done some initial work [here](https://github.com/clevertech/SuffolkCostLab/pull/309) that maybe can be reused, although more effort is needed.

@gimenete what are your thoughts on this? 😄

**Comment by gimenete** [comment]
Hi @kutyel 

That's an interesting feature/change. However I tend to prefer not to add layers of complexity if not needed. For example I'm not sure if this could have problems with remote debugging or things like that.

If there were something new that this would provide us, I would consider it.

Thanks!

**Comment by chadfurman** [comment]
We should close this.
