### ISSUE TITLE
Use postgres:alpine and redis:alpine 

### ISSUE THREAD

**Issue by keepitsimple** [clevertech/boilerplate#24]
I propose to use official alpine images for postgres & redis

**Comment by gimenete** [comment]
@keepitsimple does it make the images smaller?

**Comment by keepitsimple** [comment]
@gimenete Yes of course! The difference is significant. For example:
* redis:4.0.10-alpine 
Virtual Size: ~ 28.65 Mb
(total size of all layers on-disk)
* redis:4.0.10
Virtual Size: ~ 83.39 Mb
(total size of all layers on-disk)
* postgres:9.6.9
Virtual Size: ~ 235.37 Mb
(total size of all layers on-disk)
* postgres:9.6.9-alpine
Virtual Size: ~ 39.88 Mb
(total size of all layers on-disk)

**Comment by gimenete** [comment]
@gmotruk @acaraion can you take a look?

I'm wondering if the env variables that they use are the same

**Comment by thomast74** [comment]
both postgres and redis are using now the latest version and alpine docker images
